default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-app_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: rails-app_test
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
