default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-app_development
  host: localhost
  username: oktaexample
  password: oktaexample

test:
  <<: *default
  database: rails-app_test
  username: oktaexample
  password: oktaexample

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
